sudo: required
services:
    - docker

before_install:
    - docker build -t shivambehal/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shivambehal/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-318854857817"
    bucket_path: "docker-react"
    on:
        branch: master
    access-key-id: "$aws_access_key_id"
    secret_acess_key: "$aws_secret_access_key"