sudo: required
services:
    - docker

before_install:
    - docker build -t shivambehal/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shivambehal/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-134150706793"
    bucket_path: "docker-react"
    on:
        branch: master
    access-key-id: 
        secure: $aws_access_key_id
    secret_acess_key: 
        secure: "$aws_secret_access_key"
    session_token:
        secure: "$aws_session_token"